<?php

namespace Augwa\QuickBooks\Enum;

/**
 * Enumeration of Desktop Entity Type For ThirdPartyAppId Migration
 *
 * Class DesktopEntityTypeEnum
 * @package Augwa\QuickBooks\Enum
 */
class DesktopEntityTypeEnum
{

    const ANY = 'ANY';
    const CREDIT_CARD = 'CREDIT_CARD';
    const DEPOSIT = 'DEPOSIT';
    const CHECK = 'CHECK';
    const INVOICE = 'INVOICE';
    const CASHSALE = 'CASHSALE';
    const CREDIT_MEMO = 'CREDIT_MEMO';
    const APP_PAY = 'APP_PAY';
    const GENERAL_JOURNAL = 'GENERAL_JOURNAL';
    const BILL = 'BILL';
    const GENERIC = 'GENERIC';
    const CREDIT_CARD_REFUND = 'CREDIT_CARD_REFUND';
    const BILL_REFUND = 'BILL_REFUND';
    const AR_CREDIT_CARD_REFUND = 'AR_CREDIT_CARD_REFUND';
    const BILL_CHECK = 'BILL_CHECK';
    const BILL_CREDIT_CARD = 'BILL_CREDIT_CARD';
    const SALES_TAX_PAYMENT = 'SALES_TAX_PAYMENT';
    const PURCHASE_ORDER = 'PURCHASE_ORDER';
    const INVENTORY_ADJUSTMENT = 'INVENTORY_ADJUSTMENT';
    const INVENTORY_RECEIPT = 'INVENTORY_RECEIPT';
    const PAYCHECK = 'PAYCHECK';
    const LIABILITY_CHECK = 'LIABILITY_CHECK';
    const BEGIN_BALANCE_CHECK = 'BEGIN_BALANCE_CHECK';
    const LIABILITY_ADJUSTMENT = 'LIABILITY_ADJUSTMENT';
    const ESTIMATE = 'ESTIMATE';
    const STATEMENT_CHARGE = 'STATEMENT_CHARGE';
    const TRANSFER = 'TRANSFER';
    const SALESORDER = 'SALESORDER';
    const QBRSLIABCHECK = 'QBRSLIABCHECK';
    const BUILDASSEMBLY = 'BUILDASSEMBLY';
    const EFPLIABCHECK = 'EFPLIABCHECK';
    const PRIOR_PMT = 'PRIOR_PMT';
    const LIAB_REFUND_CHECK = 'LIAB_REFUND_CHECK';
    const ITEM_SERVICE = 'ITEM_SERVICE';
    const ITEM_INVENTORY = 'ITEM_INVENTORY';
    const ITEM_ASSEMBLY = 'ITEM_ASSEMBLY';
    const ITEM_PART = 'ITEM_PART';
    const ITEM_FIXEDASSET = 'ITEM_FIXEDASSET';
    const ITEM_CHARGES = 'ITEM_CHARGES';
    const ITEM_SUBTOTAL = 'ITEM_SUBTOTAL';
    const ITEM_GROUP = 'ITEM_GROUP';
    const ITEM_DISCOUNT = 'ITEM_DISCOUNT';
    const ITEM_PAYMENT = 'ITEM_PAYMENT';
    const ITEM_TAXCOMP = 'ITEM_TAXCOMP';
    const ITEM_TAXGROUP = 'ITEM_TAXGROUP';
    const ITEM_GROUPEND = 'ITEM_GROUPEND';
    const ITEM_PURCHASE = 'ITEM_PURCHASE';
    const ITEM_PO = 'ITEM_PO';
    const ITEM_INVOICE = 'ITEM_INVOICE';
    const ITEM_ALLITEMS = 'ITEM_ALLITEMS';
    const ITEM_NOTAXES = 'ITEM_NOTAXES';
    const ITEM_SERVICES_AND_CHARGES = 'ITEM_SERVICES_AND_CHARGES';
    const ITEM_REAL_GROUP_END = 'ITEM_REAL_GROUP_END';
    const ITEM_MAX = 'ITEM_MAX';
    const CUSTOMER = 'CUSTOMER';
    const VENDOR = 'VENDOR';
    const EMPLOYEE = 'EMPLOYEE';
    const OTHERNAME = 'OTHERNAME';
    const NULLLINKTYPE = 'NULLLINKTYPE';
    const UNUSED1 = 'UNUSED1';
    const REFUNDCHECKTOCRMEMO = 'REFUNDCHECKTOCRMEMO';
    const INVOICETOCRMEMO = 'INVOICETOCRMEMO';
    const INVOICETOPAYMENT = 'INVOICETOPAYMENT';
    const INVOICETODISCOUNT = 'INVOICETODISCOUNT';
    const BILLTOCHECK = 'BILLTOCHECK';
    const BILLTOCCARD = 'BILLTOCCARD';
    const BILLTOCREDIT = 'BILLTOCREDIT';
    const DEPOSITTOPAYMENT = 'DEPOSITTOPAYMENT';
    const REFUNDCHECKTOPAYMENT = 'REFUNDCHECKTOPAYMENT';
    const INVOICETOPMTLINE = 'INVOICETOPMTLINE';
    const INVOICETOCREDITLINE = 'INVOICETOCREDITLINE';
    const BILLTOCREDITLINE = 'BILLTOCREDITLINE';
    const CREDLINETODISCLINE = 'CREDLINETODISCLINE';
    const PURCHASEORDERTORECEIPT = 'PURCHASEORDERTORECEIPT';
    const BILLTODISCOUNT = 'BILLTODISCOUNT';
    const INVOICETODISCOUNTLINE = 'INVOICETODISCOUNTLINE';
    const INVOICETOESTIMATEQTY = 'INVOICETOESTIMATEQTY';
    const INVOICETOESTIMATEAMT = 'INVOICETOESTIMATEAMT';
    const INVOICETOSALESORDERQTY = 'INVOICETOSALESORDERQTY';
    const INVOICETOSALESORDERAMT = 'INVOICETOSALESORDERAMT';
    const JOURNALENTRYTOCRMEMO = 'JOURNALENTRYTOCRMEMO';
    const AR_CCREFUND_TO_CREDITMEMO = 'AR_CCREFUND_TO_CREDITMEMO';
    const AR_CCREFUND_TO_PAYMENT = 'AR_CCREFUND_TO_PAYMENT';
    const AR_CCREFUND_TO_JOURNAL = 'AR_CCREFUND_TO_JOURNAL';
    const GIRO_TO_CHECK = 'GIRO_TO_CHECK';
    const ITEM = 'ITEM';
    const DEPARTMENT = 'DEPARTMENT';
    const USERS = 'USERS';
    const KLASS = 'KLASS';
    const PAYMENT_METHOD = 'PAYMENT_METHOD';
    const TERM = 'TERM';
    const BUDGET = 'BUDGET';
    const TAX_CODE = 'TAX_CODE';
    const TAX_CODE_RATE = 'TAX_CODE_RATE';
    const TAX_AGENCY = 'TAX_AGENCY';
    const ATTACHABLE = 'ATTACHABLE';
    const ACCOUNT = 'ACCOUNT';
    const PREFERENCES = 'PREFERENCES';

}