<?php

namespace Augwa\QuickBooks\Enum;

/**
 * Enumeration of Qbo Entity Type For AppId Migration
 *
 * Class QboEntityTypeEnum
 * @package Augwa\QuickBooks\Enum
 */
class QboEntityTypeEnum
{

    const CUSTOMER = 'CUSTOMER';
    const VENDOR = 'VENDOR';
    const EMPLOYEE = 'EMPLOYEE';
    const CREDIT_CARD = 'CREDIT_CARD';
    const CHECK = 'CHECK';
    const INVOICE = 'INVOICE';
    const RECEIVED_PAYMENT = 'RECEIVED_PAYMENT';
    const GENERAL_JOURNAL = 'GENERAL_JOURNAL';
    const BILL = 'BILL';
    const CREDIT_CARD_CREDIT = 'CREDIT_CARD_CREDIT';
    const BILL_CREDIT = 'BILL_CREDIT';
    const CHARGE_CREDIT = 'CHARGE_CREDIT';
    const BILL_CHECK = 'BILL_CHECK';
    const BILL_CREDIT_CARD = 'BILL_CREDIT_CARD';
    const CHARGE = 'CHARGE';
    const TRANSFER = 'TRANSFER';
    const RECEIVED_MONEY = 'RECEIVED_MONEY';
    const STATEMENT = 'STATEMENT';
    const REIMB_CHARGE = 'REIMB_CHARGE';
    const CASH_PURCHASE = 'CASH_PURCHASE';
    const CASH_SALE = 'CASH_SALE';
    const CREDIT_MEMO = 'CREDIT_MEMO';
    const CREDIT_REFUND = 'CREDIT_REFUND';
    const ESTIMATE = 'ESTIMATE';
    const INVENTORY_QUANTITY_ADJUSTMENT = 'INVENTORY_QUANTITY_ADJUSTMENT';
    const PURCHASE_ORDER = 'PURCHASE_ORDER';
    const PAYROLL_CHECK = 'PAYROLL_CHECK';
    const TAX_PAYMENT = 'TAX_PAYMENT';
    const PAYROLL_ADJUSTMENT_V2 = 'PAYROLL_ADJUSTMENT_V2';
    const PAYROLL_REFUND = 'PAYROLL_REFUND';
    const GLOBAL_TAX_PAYMENT = 'GLOBAL_TAX_PAYMENT';
    const GLOBAL_TAX_ADJUSTMENT = 'GLOBAL_TAX_ADJUSTMENT';
    const JOB_INVOICE = 'JOB_INVOICE';
    const ITEM = 'ITEM';
    const GENERIC_EXPENSE = 'GENERIC_EXPENSE';
    const TIME_ACTIVITY = 'TIME_ACTIVITY';
    const DEPARTMENT = 'DEPARTMENT';
    const USERS = 'USERS';
    const KLASS = 'KLASS';
    const PAYMENT_METHOD = 'PAYMENT_METHOD';
    const MEMORIZED_TRANSACTION = 'MEMORIZED_TRANSACTION';
    const TERM = 'TERM';
    const BUDGET = 'BUDGET';
    const TAX_CODE = 'TAX_CODE';
    const TAX_CODE_RATE = 'TAX_CODE_RATE';
    const TAX_AGENCY = 'TAX_AGENCY';
    const ATTACHABLE = 'ATTACHABLE';
    const ACCOUNT = 'ACCOUNT';
    const PREFERENCES = 'PREFERENCES';
    const JOURNAL_CODE = 'JOURNAL_CODE';
    const DISCOUNT_RATE = 'DISCOUNT_RATE';
    const BANKING_TRANSACTIONS = 'BANKING_TRANSACTIONS';
    const BUSINESS_TERMS = 'BUSINESS_TERMS';
    const LIABILITY_CHECK = 'LIABILITY_CHECK';
    const LIABILITY_CREDIT_CARD = 'LIABILITY_CREDIT_CARD';
    const LIABILITY_REFUND = 'LIABILITY_REFUND';
    const PRIOR_LIABILITY_PAYMENTS = 'PRIOR_LIABILITY_PAYMENTS';
    const LIABILITY_EPAY = 'LIABILITY_EPAY';
    const LIABILITY_MMAP = 'LIABILITY_MMAP';
    const TAX_CREDIT_UTILISE = 'TAX_CREDIT_UTILISE';
    const TAX_CREDIT_DEFER = 'TAX_CREDIT_DEFER';
    const TAX_CREDIT_REVERSE = 'TAX_CREDIT_REVERSE';
    const TAX_CREDIT_REFUND = 'TAX_CREDIT_REFUND';
    const GROSS_ADJUSTMENT = 'GROSS_ADJUSTMENT';
    const REVERSE_CHARGE = 'REVERSE_CHARGE';
    const DD_CHECK = 'DD_CHECK';
    const PAYCHECK = 'PAYCHECK';
    const PAYROLL_ADJUSTMENT = 'PAYROLL_ADJUSTMENT';
    const PAYROLL_YTD = 'PAYROLL_YTD';
    const SDK_USERS = 'SDK_USERS';
    const PAYROLL_ITEMS = 'PAYROLL_ITEMS';
    const PAY_GROUPS = 'PAY_GROUPS';
    const PAID_TIME_OFF_ENTRIES = 'PAID_TIME_OFF_ENTRIES';
    const TAX_JURISDICTIONS = 'TAX_JURISDICTIONS';
    const MEMORIZED_REPORTS = 'MEMORIZED_REPORTS';
    const OLB_FINANCIAL_INSTITUTIONS = 'OLB_FINANCIAL_INSTITUTIONS';
    const DIRECT_DEPOSIT_BANK_INFO = 'DIRECT_DEPOSIT_BANK_INFO';
    const REMINDERS = 'REMINDERS';
    const PAYROLL_FORMS = 'PAYROLL_FORMS';
    const EPAY_BANK_ACCOUNT_INFO = 'EPAY_BANK_ACCOUNT_INFO';
    const EPAY_AGENCY_CREDENTIALS = 'EPAY_AGENCY_CREDENTIALS';
    const EFILE_ENROLLMENT = 'EFILE_ENROLLMENT';
    const TAXRETURNLINES = 'TAXRETURNLINES';
    const NOTES = 'NOTES';
    const PRINT_PREF = 'PRINT_PREF';
    const MANAGEMENT_REPORT = 'MANAGEMENT_REPORT';
    const OLB_RULES = 'OLB_RULES';
    const DESKTOPIMPORT_SEED_QOH = 'DESKTOPIMPORT_SEED_QOH';

}