<?php

namespace Augwa\QuickBooks\Enum;

/**
 * Enumeration of item service type for India sales tax
 *
 * Class ServiceTypeEnum
 * @package Augwa\QuickBooks\Enum
 */
class ServiceTypeEnum
{

    const ADVT = 'ADVT';
    const AIRPORTSERVICES = 'AIRPORTSERVICES';
    const AIRTRANSPORT = 'AIRTRANSPORT';
    const AIRTRVLAGNT = 'AIRTRVLAGNT';
    const ARCHITECT = 'ARCHITECT';
    const ASSTMGMT = 'ASSTMGMT';
    const ATMMAINTENANCE = 'ATMMAINTENANCE';
    const AUCTIONSERV = 'AUCTIONSERV';
    const AUTHSERST = 'AUTHSERST';
    const BANKANDFIN = 'BANKANDFIN';
    const BEAUTYPARLOR = 'BEAUTYPARLOR';
    const BROADCAST = 'BROADCAST';
    const BUSINESSAUX = 'BUSINESSAUX';
    const BUSINESSEXHIBITION = 'BUSINESSEXHIBITION';
    const BUSINESSSUPPORTSERV = 'BUSINESSSUPPORTSERV';
    const CA = 'CA';
    const CABLEOPTR = 'CABLEOPTR';
    const CARGOHAND = 'CARGOHAND';
    const CLEANINGSERV = 'CLEANINGSERV';
    const CLEARANDFORW = 'CLEARANDFORW';
    const CLUBSANDASSSERVICE = 'CLUBSANDASSSERVICE';
    const COMMCOACHORTRAINING = 'COMMCOACHORTRAINING';
    const CONSENG = 'CONSENG';
    const CONSTRCOMMERCIALCOMPLEX = 'CONSTRCOMMERCIALCOMPLEX';
    const CONTAINERRAILTRANS = 'CONTAINERRAILTRANS';
    const CONVSERV = 'CONVSERV';
    const COSTACC = 'COSTACC';
    const COURIER = 'COURIER';
    const CREDITCARD = 'CREDITCARD';
    const CREDITRATAGNCY = 'CREDITRATAGNCY';
    const CRUISESHIPTOUR = 'CRUISESHIPTOUR';
    const CS = 'CS';
    const CUSHOUSEAG = 'CUSHOUSEAG';
    const DESIGNSERV = 'DESIGNSERV';
    const DEVELOPSUPPLYCONTENT = 'DEVELOPSUPPLYCONTENT';
    const DREDGING = 'DREDGING';
    const DRYCLEANING = 'DRYCLEANING';
    const ERECTIONCOMMORINSTALL = 'ERECTIONCOMMORINSTALL';
    const EVENTMGMT = 'EVENTMGMT';
    const FASHIONDES = 'FASHIONDES';
    const FOREXBROKING = 'FOREXBROKING';
    const FORWARDCONTRACT = 'FORWARDCONTRACT';
    const FRANCHISESERV = 'FRANCHISESERV';
    const GENERALINSURANCE = 'GENERALINSURANCE';
    const GOODSTRANSPORT = 'GOODSTRANSPORT';
    const HEALTHCLUBANDFITNESS = 'HEALTHCLUBANDFITNESS';
    const INFORMATIONSERV = 'INFORMATIONSERV';
    const INSURAUX = 'INSURAUX';
    const INTDEC = 'INTDEC';
    const INTELLECTUALPROPERTY = 'INTELLECTUALPROPERTY';
    const INTERNATIONALAIRTRAVEL = 'INTERNATIONALAIRTRAVEL';
    const INTERNETCAFE = 'INTERNETCAFE';
    const INTERNETTELEPHONY = 'INTERNETTELEPHONY';
    const LIFEINS = 'LIFEINS';
    const MAILLISTCOMPILE = 'MAILLISTCOMPILE';
    const MANDAPKEEPER = 'MANDAPKEEPER';
    const MANPWRRECRUIT = 'MANPWRRECRUIT';
    const MGMTCONSUL = 'MGMTCONSUL';
    const MGMTMAINTREPAIR = 'MGMTMAINTREPAIR';
    const MININGOIL = 'MININGOIL';
    const MKTRESAGNCY = 'MKTRESAGNCY';
    const ONLINEINFORMRETRIEVAL = 'ONLINEINFORMRETRIEVAL';
    const OPINIONPOLL = 'OPINIONPOLL';
    const OUTDOORCATERING = 'OUTDOORCATERING';
    const PACKAGINGSERV = 'PACKAGINGSERV';
    const PANDALSHAMIANA = 'PANDALSHAMIANA';
    const PHOTOGRAPHY = 'PHOTOGRAPHY';
    const PORT = 'PORT';
    const PORTSER = 'PORTSER';
    const PROCESSCLEARHOUSE = 'PROCESSCLEARHOUSE';
    const PUBLICRELATIONMGMT = 'PUBLICRELATIONMGMT';
    const RAILTRAVELAGNT = 'RAILTRAVELAGNT';
    const REALESTAGT = 'REALESTAGT';
    const RECOVERYAGENTS = 'RECOVERYAGENTS';
    const REGISTRARSERV = 'REGISTRARSERV';
    const RENTACAB = 'RENTACAB';
    const RENTINGIMMOVABLEPROP = 'RENTINGIMMOVABLEPROP';
    const RESIDENTIALCOMPLEXCONST = 'RESIDENTIALCOMPLEXCONST';
    const SALEOFSPACEFORADVT = 'SALEOFSPACEFORADVT';
    const SCANDTECHCONSUL = 'SCANDTECHCONSUL';
    const SECAG = 'SECAG';
    const SERVICESPROVIDEDFORTRANSACTION = 'SERVICESPROVIDEDFORTRANSACTION';
    const SHARETRANSFERSERV = 'SHARETRANSFERSERV';
    const SHIPMGMT = 'SHIPMGMT';
    const SITEPREP = 'SITEPREP';
    const SOUNDRECORD = 'SOUNDRECORD';
    const SPONSORSHIP = 'SPONSORSHIP';
    const STAG = 'STAG';
    const STOCKBROKING = 'STOCKBROKING';
    const STOCKEXCHGSERV = 'STOCKEXCHGSERV';
    const STORANDWAREHOUSING = 'STORANDWAREHOUSING';
    const SUPPLYTANGIBLEGOODS = 'SUPPLYTANGIBLEGOODS';
    const SURVEYANDMAPMAKING = 'SURVEYANDMAPMAKING';
    const SURVEYMINERALS = 'SURVEYMINERALS';
    const TECHINSPECTION = 'TECHINSPECTION';
    const TECHTESTING = 'TECHTESTING';
    const TELECOMMUNICATIONSERV = 'TELECOMMUNICATIONSERV';
    const TELEVISIONANDRADIO = 'TELEVISIONANDRADIO';
    const TOUROP = 'TOUROP';
    const TRANSPORTPIPELINE = 'TRANSPORTPIPELINE';
    const TRAVELAGENT = 'TRAVELAGENT';
    const ULIPMANAGEMENT = 'ULIPMANAGEMENT';
    const UNDERWRITER = 'UNDERWRITER';
    const VIDEOTAPEPROD = 'VIDEOTAPEPROD';
    const WORKSCONTRACT = 'WORKSCONTRACT';

}